server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
    location /api/auth/ {
        proxy_pass http://auth-service:3001/api/auth/;
        proxy_set_header Host $host;
    }
    location /api/orders/ {
        proxy_pass http://order-service:3002/api/orders/;
        proxy_set_header Host $host;
    }
    location /api/products/ {
        proxy_pass http://product-service:3000/api/products/;
        proxy_set_header Host $host;
    }
    location /api/cart/ {
        proxy_pass http://product-service:3000/api/cart/;
        proxy_set_header Host $host;
    }
}