server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
    location /api/auth/ {
        proxy_pass http://auth:3001/api/auth/;
        proxy_set_header Host $host;
    }
    location /api/order/ {
        proxy_pass http://order:3002/api/order/;
    }
    location /api/product/ {
        proxy_pass http://product:3000/api/product/;
    }
}